all_matches=false
check_updates=true
command_stt="google"
conversation_mode=true
dictionary="stt_engines/pocketsphinx/jarvis-dictionary.dic"
google_speech_api_key=""
language="en_EN"
language_model="stt_engines/pocketsphinx/jarvis-languagemodel.lm"
max_noise_duration_to_kill="10" # default 10
min_noise_duration_to_start="0.1" # default 0.1
min_noise_perc_to_start="1%" # default 1%
min_silence_duration_to_stop="0.5" # default 0.5
min_silence_level_to_stop="1%" # default 1%
play_hw=false
pocketsphinxlog="/dev/null" # can get very big on long run
rec_hw=false
separator=""
tmp_folder="/tmp"
trigger='jarvis'
trigger_mode="magic_word"
trigger_stt="snowboy"
tts_engine="svox_pico"
username="`whoami`"
wit_server_access_token=""
hello=$(if [ $(date +%H) -lt 18 ]; then echo Bonjour; else echo Bonsoir; fi)
command_failed="Cette commande a retourné une erreur"
